version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@0.5.19
jobs:
  test-shared:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.18.0'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/install-packages:
          app-dir: ./shared
      - run:
          working_directory: ./shared
          command: npm install --save-dev jest-junit
      - run:
          name: spinning up ganache
          working_directory: ./shared
          command: npm run start-ganache
          background: true
      - run:
          working_directory: ./shared
          command: mkdir -p _out/unit _out/e2e
      - run:
          working_directory: ./shared
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-test.xml
            JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true
      - run:
          working_directory: ./shared
          command: npm run test:e2e -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-e2e.xml
            JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true
      - store_test_results:
          path: ./shared/_out
      - store_artifacts:
          path: ./shared/_out

  test-rewards-service:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.18.0'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - node/install-packages:
          app-dir: ./shared
      - run:
          working_directory: ./shared
          command: npm run build
      - node/install-packages:
          app-dir: ./rewards-service
      - run:
          working_directory: ./rewards-service
          command: npm run build
      - run:
          working_directory: ./rewards-service
          command: npm install --save-dev jest-junit
      - run:
          working_directory: ./rewards-service
          command: mkdir -p _out/unit _out/e2e
      - run:
          working_directory: ./rewards-service
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-test.xml
            JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true
      - run:
          working_directory: ./rewards-service
          command: npm run test:e2e -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-e2e.xml
            JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true
      - store_test_results:
          path: ./rewards-service/_out
      - store_artifacts:
          path: ./rewards-service/_out

  build-and-release-to-staging-rewards-service:
    machine: true
    steps:
        - checkout
        - node/install:
            node-version: '12.18.0'
        - docker/install-docker
        - run: ./rewards-service/boyar/create-version-file.sh
        - node/install-packages:
            app-dir: ./shared
        - run:
            working_directory: ./shared
            command: npm run build
        - node/install-packages:
            app-dir: ./rewards-service
        - run:
            working_directory: ./rewards-service
            command: npm run build
        - run:
            working_directory: ./rewards-service
            command: ./boyar/create-version-file.sh
        - run:
            working_directory: ./rewards-service
            command: ./boyar/docker-build.sh
        - run: ./.circleci/rewards-service/release-to-staging.sh

  build-and-release-rewards-service:
    machine: true
    steps:
        - checkout
        - node/install:
            node-version: '12.18.0'
        - docker/install-docker
        - run: ./rewards-service/boyar/create-version-file.sh
        - node/install-packages:
            app-dir: ./shared
        - run:
            working_directory: ./shared
            command: npm run build
        - node/install-packages:
            app-dir: ./rewards-service
        - run:
            working_directory: ./rewards-service
            command: npm run build
        - run:
            working_directory: ./rewards-service
            command: ./boyar/create-version-file.sh
        - run:
            working_directory: ./rewards-service
            command: ./boyar/docker-build.sh
        - run: ./.circleci/rewards-service/release.sh

workflows:
  build-and-test:
    jobs:
      - test-shared
      - test-rewards-service
      - build-and-release-to-staging-rewards-service
      - build-and-release-rewards-service:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master