version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.19
jobs:
  test-shared:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: '12.13.0'
      - docker/install-docker
      - run: node --version
      - run: npm --version
      - run: docker --version
      - run: env
      - run: 
          working_directory: ./shared
          command: npm install
      - run: 
          working_directory: ./shared
          command: npm install --save-dev jest-junit
      - run:
          name: spinning up ganache
          working_directory: ./shared
          command: npm run start-ganache
          background: true
      - run: 
          working_directory: ./shared
          command: mkdir -p _out/unit _out/e2e
      - run: 
          working_directory: ./shared
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-test.xml
      - run:
          working_directory: ./shared
          command: npm run test:e2e -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./_out
            JEST_JUNIT_OUTPUT_NAME: junit-e2e.xml
      - store_test_results:
          path: ./shared/_out
      - store_artifacts:
          path: ./shared/_out    

  
workflows:
  build-and-test:
    jobs:
      - test-shared
