version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile-app.test
        ports:
            - 8080
    signer:
        image: orbsnetwork/signer:experimental
        ports:
            - 7777:7777
        volumes:
            - ./signer/keys.json:/run/secrets/keys.json
        command: /opt/orbs/orbs-signer -listen :7777 -config /run/secrets/keys.json
    ganache:
        image: trufflesuite/ganache-cli
        ports:
            - 7545
        command: -p 7545 -i 5777 -a 100 --gasLimit 0x7FFFFFFF --gasPrice 40000000000 -m  "vanish junk genuine web seminar cook absurd royal ability series taste method identify elevator liquid"